---
- name: Install Nginx
  hosts: "{{ instance_dns }}"

  become: true

  tasks:
    - name: Update package cache (for Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Update package cache (for Red Hat-based systems)
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Nginx (for Red Hat-based systems)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
